# Generated by Django 5.0 on 2024-04-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_paid",
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
