# Generated by Django 5.0 on 2024-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_total_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
