# Generated by Django 5.0 on 2024-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
