# Generated by Django 5.0 on 2024-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("bankak", "بنكك"), ("wallet", "محفظة الحساب")],
                default="bankak",
                max_length=20,
            ),
        ),
    ]
