# Generated by Django 5.0 on 2024-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
