# Generated by Django 5.0 on 2024-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
