# Generated by Django 5.0 on 2024-04-21 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_game_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
