# Generated by Django 5.0 on 2024-04-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_discount_discount_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["price"], "verbose_name_plural": "Cards"},
        ),
        migrations.AlterField(
            model_name="card",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_cards",
                to="shop.game",
            ),
        ),
    ]
